### ISSUE TITLE
payu automatic storage flags

### ISSUE THREAD

**Issue by navidcy** [payu-org/payu#229]
latest version of payu checks the manifests (I believe `exe.yaml`, `input.yaml`, `restart.yaml`) and figures out which drives needs to mount with a `-l storage=...` flag.

What if one has, e.g., an `.sh` script that copies files to `/g/data/` after each run but nothing in the `.yaml` files points to `/g/data/`? Will payu figure it out? I guess not, right?

**Comment by aidanheerdegen** [comment]
No it can't do that. If the storage point isn't already mounted because other stuff is read from there in one of the manifests you'll have to add that manually.

Is the information in the docs sufficient to tell you what options you need to set?

https://payu.readthedocs.io/en/latest/config.html#configuration-settings

**Comment by navidcy** [comment]
Yes this is helpful.
